# Builds a dockerimage and then runs tests from within the docker environment

name: CI with docker build
on:
  pull_request:
    branches:
    - develop
    - main

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test with Docker
        run: |
          docker build -t cad_to_h5m .
          docker run --rm --network host cad_to_h5m  /bin/bash -c "bash run_tests.sh"
