
# This CI will lauch a Docker image that contains all the dependencies required
# within that image the pytest test suite is run 


name: CI with install

on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fusion-energy/cad_to_h5m:dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: install package
        run: |
          pip install -r requirements-test.txt --user
          python setup.py install

      - name: Run test_utils
        run: |
          pytest tests/test_python_api.py -v 
