# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  pull_request:
    branches:
    - develop
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    ports:
      # Opens ports needed for Cubit license server communication on the host
      - 5053:5053
      - 5119:5119
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and test with Docker
        run: |
          printf '${{ github.license_file }}' >> license.lic
          cat license.lic
          docker build -t cad_to_h5m .
          docker run --rm cad_to_h5m  /bin/bash -c "bash run_tests.sh"
